import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider, Modal } from "@/context/Modal";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FLASH - ahhhhhh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-background overflow-y-hidden`}>
        <ModalProvider >
          <NavBar />
          {children}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
}
